# ==============================================
# VISUAL PLATFORM - PRE-COMMIT HOOKS
# ==============================================

repos:
  # Hooks généraux
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ['--maxkb=500']
      - id: mixed-line-ending
        args: ['--fix=lf']

  # TypeScript/JavaScript - ESLint
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.46.0
    hooks:
      - id: eslint
        files: \.(js|jsx|ts|tsx)$
        additional_dependencies:
          - "@typescript-eslint/eslint-plugin@^6.0.0"
          - "@typescript-eslint/parser@^6.0.0"
          - "eslint-config-prettier@^8.8.0"
          - "eslint-plugin-react@^7.33.0"
          - "eslint-plugin-react-hooks@^4.6.0"

  # TypeScript/JavaScript - Prettier
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0
    hooks:
      - id: prettier
        files: \.(js|jsx|ts|tsx|json|css|md|yaml|yml)$
        additional_dependencies:
          - "prettier@^3.0.0"
          - "@trivago/prettier-plugin-sort-imports@^4.1.1"

  # Python - Black (formatage)
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        language_version: python3
        files: \.py$

  # Python - Ruff (linting rapide)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.278
    hooks:
      - id: ruff
        files: \.py$
        args: [--fix, --exit-non-zero-on-fix]

  # Python - isort (tri des imports)
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        files: \.py$
        args: ["--profile", "black"]

  # Sécurité - Détection de secrets
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: package.lock.json

  # SQL - Formatage
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 2.1.3
    hooks:
      - id: sqlfluff-lint
        files: \.sql$
      - id: sqlfluff-fix
        files: \.sql$

  # Docker - Hadolint
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint-docker
        files: Dockerfile

  # Commits conventionnels
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.4.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]

# Configuration globale
default_stages: [commit]
fail_fast: false