name: CI
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  node-ci:
    name: Frontend (Node 20)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install deps
        run: npm ci
      - name: Lint & Build
        run: |
          npm run lint --if-present
          npm run build --if-present
      - name: Test
        run: npm test --if-present

  python-ci:
    name: Backend (Python 3.11)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f server/requirements.txt ]; then pip install -r server/requirements.txt; fi
          pip install prometheus-client asyncpg stripe
      - name: Lint & Test
        run: |
          if [ -f server/pytest.ini ] || [ -f pytest.ini ]; then pytest -q; else echo "no tests"; fi

  sitemaps:
    name: Generate Sitemaps
    runs-on: ubuntu-latest
    needs: [node-ci, python-ci]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - name: Generate localized sitemaps
        run: |
          if [ -f scripts/generate_sitemaps.mjs ]; then node scripts/generate_sitemaps.mjs; else echo "no sitemap script"; fi
      - name: Upload sitemap artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sitemaps
          path: public/sitemaps/*.xml
