name: Docker Publish
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          # Adjust image name to your registry / namespace
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/visual-platform:latest
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/visual-platform:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/visual-platform:buildcache,mode=max
